AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Test Lambda with spring boot.

Globals:
  Function:
    Runtime: java8
    Environment:
      Variables:
        TABLE_NAME: !Ref Table

Resources:
  GLSpringBootFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.globallogic.gllambdademo.LambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/gl-lambda-demo-0.0.1-SNAPSHOT.jar
      MemorySize: 1512
      Policies: AmazonDynamoDBFullAccess #AWSLambdaBasicExecutionRole
      Timeout: 120
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: Speaker

Outputs:
  GLSpringBootApi:
    Description: URL for lambda application demo
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/user'
    Export:
      Name: GLSpringBootApi
